Tourservice services
EspadaKomanda/vtb-api-2024 pull request #1
Opened 2024-10-30 18:41 UTC by Ferru5Manus

2024-10-30 19:05 UTC, ReallyWeirdCat requested changes

2024-10-30 19:05 UTC, ReallyWeirdCat commented on TourService/Attributes/Validation/TourName.cs
> +        private static readonly string[] ProhibitedWords = { "admin", "administrator", "root" };
Я думаю тут лучше вспомнить идею с rockyou.txt и замутить что-то на подобии этого. Вместо текстового файла можно наверное и бдшку sqlite подкрутить, чтобы не делать отдельный микросервис, еще потом через том докера её протянуть. Пока кринжово, что в каждом аттрибуте лежат эти переменные, лучше вести большой общий список

2024-10-30 19:05 UTC, ReallyWeirdCat commented on TourService/Database/Models/Tour.cs
> +        public int Price {get; set; }
double/float

2024-10-30 19:05 UTC, ReallyWeirdCat commented on TourService/Attributes/Validation/TourPrice.cs
> +            if (value is int price)
double/float

2024-10-30 19:05 UTC, ReallyWeirdCat commented on TourService/Database/Models/Benefit.cs
> +        [TourName]
TourName потому что у имен суть одна и та же?

2024-10-30 19:05 UTC, ReallyWeirdCat commented on TourService/Kafka/KafkaTopicManager.cs
> +    /// <summary>
Думаю лучше писать на русском их, т.к. уже практикуется в auth и user (Открыт к обсуждению все же)

2024-10-30 19:05 UTC, ReallyWeirdCat commented on TourService/appsettings.Development.json
Просьба кинуть это в .gitignore, уже соблюдается в двух сервисах. Нужно, т.к. там токены и строки доступа к бд есть

2024-10-30 19:06 UTC, Ferru5Manus commented on TourService/Attributes/Validation/TourName.cs
> +        private static readonly string[] ProhibitedWords = { "admin", "administrator", "root" };
Я пока не копал это дальше и это не самая важная часть, пусть пока будет так

2024-10-30 19:06 UTC, Ferru5Manus commented on TourService/Database/Models/Tour.cs
> +        public int Price {get; set; }
Поправлю

2024-10-30 19:06 UTC, Ferru5Manus commented on TourService/Attributes/Validation/TourPrice.cs
> +            if (value is int price)
Аналогично

2024-10-30 19:07 UTC, Ferru5Manus commented on TourService/Database/Models/Benefit.cs
> +        [TourName]
Да, а просто нейм с чем-то пересеклось и у меня почему-то в сборке не видело аттрибут

2024-10-30 19:07 UTC, Ferru5Manus commented on TourService/Kafka/KafkaTopicManager.cs
> +    /// <summary>
Старый код из Gazprom, ещё ты писал эти саммари

2024-10-30 19:08 UTC, Ferru5Manus commented on TourService/appsettings.Development.json
Поняо

2024-11-02 08:26 UTC, ReallyWeirdCat approved these changes

2024-11-02 08:30 UTC, ReallyWeirdCat approved these changes

2024-11-10 14:30 UTC, merged